* What is notmuch-to-kindle?

notmuch-to-kindle is small tool to transfer notmuch emails to Kindle in mobi format, using calibre's utility programs (most importantly ebook-convert).

It currently extracts all mime parts, post-processes some (at this time, only .html and .doc, future versions will support epub as well), and copies all acceptable files (.mobi, .azw, .pdf) to your chosen Kindle search path.

.doc is converted via html through abiword. If it is missing, notmuch-to-kindle will output an error to stderr and proceed, ignoring the attached file.

* Requirements
- Calibre's command-line tools (ebook-convert).
- Python notmuch bindings.
  
* Usage
On invocation the program will look for the ~/.notmuch-to-kindlerc file, which should contain something like this:

: [main]
: tag=read/review
: max=15
: target=/media/Kindle/documents/mail
: [ebook-convert]
: input_profile=kindle

These are all the options available. Target specifies the directory to copy the finished .mobi files to, max is how many files to copy (max), and tag is the tag used to mark the emails to export from notmuch.

* What doesn't work yet?
- Automatic mounting of the device. I wanted to use Calibre's ebook-device, but for reasons that escape me, I can't get ebook-device cp to eat my newly-produced ebook files. Suggestions/patches are welcome of course.
- Text-only email. Currently only html mime parts and attachments are used.
- All attachments. Some attachments with unicoded file names won't be extracted.
