* What is?

notmuch-to-kindle is small tool to transfer notmuch emails to Kindle in mobi format, using calibre's utility programs (most importantly ebook-convert).

* Requirements
- Calibre's command-line tools (ebook-convert).
- Python notmuch bindings.
  
* Usage
On invocation the program will look for the ~/.notmuch-to-kindlerc file, which should contain something like this:

: [main]
: tag=read/review
: max=15
: target=/media/Kindle/documents/mail
: [ebook-convert]
: input_profile=kindle

These are all the options available. Target specifies the directory to copy the finished .mobi files to, max is how many files to copy (max), and tag is the tag used to mark the emails to export from notmuch.

* What doesn't work yet?
- Attachments. The program should prioritize attached ebook files or PDFs -- but it doesn't. As a matter of fact, it just ignores them straight away.
- Automatic mounting of the device. I wanted to use Calibre's ebook-device, but for reasons that escape me, I can't get ebook-device cp to eat my newly-produced ebook files. Suggestions/patches are welcome of course.
- Ehrm, email character encodings. For some reason umlauts (for example) aren't decoded properly. Patches welcome here as well.
